name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.6.7
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/PashaArkus/alicee

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  dio: ^5.9.1
  flutter_local_notifications: ^20.1.0
  rxdart: ^0.28.0


  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  package_info_plus: ^9.0.0
#  open_filex: ^4.6.0
  open_file: ^3.5.11
  sensors_plus: ^7.0.0
  share_plus: ^12.0.1
  chopper: ^7.4.0
  collection: ^1.19.1
  url_launcher: ^6.3.2

dev_dependencies:
  lint: ^2.8.0